### TEST ~ API: ###
GET /api/test HTTP/1.1
Host: localhost:3000

# ---------------------------

### TEST ~ FILMS: ###
GET /api/films HTTP/1.1
Host: localhost:3000

# ---------------------------

### TEST ~ SIGN-UP: ###
POST /api/sign-up HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "Scooby!",
    "password": "Doo!" 
}

### TEST ~ SIGN-IN: ###
POST /api/sign-in HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "Scooby!",
    "password": "Doo!" 
}

# ---------------------------

### TEST ~ AUTH ###
GET /api/auth HTTP/1.1
Host: localhost:3000
Cookie: token=?; Secure; HttpOnly;
