### TEST ~ API: ###
GET /api/test HTTP/1.1
Host: localhost:3000

# ---------------------------

### TEST ~ FILMS: ###
GET /api/films HTTP/1.1
Host: localhost:3000

### TEST ~ FILMS: ###
GET /api/films/aftersun HTTP/1.1
Host: localhost:3000

# ---------------------------

### TEST ~ SHOWS: ###
GET /api/shows?film=aftersun&date=2023-02-14 HTTP/1.1
Host: localhost:3000

# ---------------------------

### TEST ~ TICKETS: ###
GET /api/tickets?user=user1 HTTP/1.1
Host: localhost:3000

# ---------------------------

### TEST ~ SEATS: ###
GET /api/screens/1/seats HTTP/1.1
Host: localhost:3000

# ---------------------------

### TEST ~ SIGN-UP: ###
POST /api/users/sign-up HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "Scooby!",
    "password": "Doo!" 
}

### TEST ~ SIGN-IN: ###
POST /api/users/sign-in HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "Scooby!",
    "password": "Doo!" 
}

### TEST ~ SIGN-IN: ###
POST /api/users/sign-in HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "Scooby!",
    "password": "Delilah?" 
}

# ---------------------------

### TEST ~ AUTH ###
# @no-cookie-jar
GET /api/auth HTTP/1.1
Host: localhost:3000
Cookie: token=?