### TEST ~ API: ###
GET /api/test HTTP/1.1
Host: localhost:3000

# ---------------------------

### TEST ~ FILMS: ###
GET /api/films HTTP/1.1
Host: localhost:3000

# ---------------------------

### TEST ~ SIGN-UP: ###
POST /api/sign-up HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "Scooby!",
    "password": "Doo!" 
}

### TEST ~ SIGN-IN: ###
POST /api/sign-in HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "Scooby!",
    "password": "Doo!" 
}

# ---------------------------

### TEST ~ AUTH ###
GET /api/auth HTTP/1.1
Host: localhost:3000
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiYWRtaW4iLCJwYXNzIjoiYWRtaW4ifQ.sD5yww1yiPvuNJEuPgBP-xni18eh0mj1shF1VmILglA;  Secure; HttpOnly;
# -> Key: NTNv7j0TuYARvmNMmWXo6fKvM4o6nv/aUi9ryX38ZH+L1bkrnD1ObOQ8JAUmHCBq7Iy7otZcyAagBLHVKvvYaIpmMuxmARQ97jUVG16Jkpkp1wXOPsrF9zwew6TpczyHkHgX5EuLg2MeBuiT/qJACs1J0apruOOJCg/gOtkjB4c=